NumPy - Numerical Python

Advantages of Numpy Arrays:
  1. Allows several Mathematical Operation.
  2. Faster Operations

In [2]:
 import numpy as np

List vs Numpy - Time Taken

In [3]:
from time import process_time

Time taken by a list

In [4]:
python_list =[i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0015375799999999273


In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.002066444999998751


Numpy Arrays

In [6]:
# list
list1 = [1,2,3,4,5]

print(list1)
type(list1)


[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
#creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [11]:
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
b.shape

(2, 4)

In [14]:
 c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
 print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholder in numpy arrays

In [15]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# create a numpy array of ones
y = np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
#array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[4.24830736e-01 3.07826855e-01 5.38785139e-01 2.44314864e-04]
 [1.79571860e-01 5.68322490e-01 5.76041443e-03 3.81090295e-01]
 [6.58902429e-01 8.68701957e-01 1.71829523e-01 8.67318907e-02]]


In [21]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,4))
print(c)

[[23 16 46 38]
 [16 20 90 22]
 [65 11 67 51]]


In [22]:
# array of evenly spaced values --> specifyn the number of vlaues required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [23]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [24]:
# convert a list to a numpy
list2 =[10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [25]:
c = np.random.randint(10,90,(5,5))
print(c)


[[30 82 84 46 33]
 [72 46 78 40 39]
 [69 83 15 62 48]
 [55 47 44 43 86]
 [19 52 37 66 80]]


In [26]:
# array dimension
print(c.shape)

(5, 5)


In [27]:
# number of dimensions
print(c.ndim)

2


In [28]:
# number of elements in an array
print(c.size)

25


In [29]:
# checking the data type of the values in the array
print(c.dtype)

int64


mathematical operations on a np array


In [30]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatinate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [31]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [33]:
print(a)
print(b)

[[0 5 5]
 [3 3 2]
 [5 7 9]]
[[13 16 18]
 [19 15 16]
 [15 15 18]]


In [34]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[13 21 23]
 [22 18 18]
 [20 22 27]]
[[-13 -11 -13]
 [-16 -12 -14]
 [-10  -8  -9]]
[[  0  80  90]
 [ 57  45  32]
 [ 75 105 162]]
[[0.         0.3125     0.27777778]
 [0.15789474 0.2        0.125     ]
 [0.33333333 0.46666667 0.5       ]]


In [35]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[13 21 23]
 [22 18 18]
 [20 22 27]]
[[-13 -11 -13]
 [-16 -12 -14]
 [-10  -8  -9]]
[[  0  80  90]
 [ 57  45  32]
 [ 75 105 162]]
[[0.         0.3125     0.27777778]
 [0.15789474 0.2        0.125     ]
 [0.33333333 0.46666667 0.5       ]]


Array Manipulation

In [38]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 1 2]
 [7 4 0]]
(2, 3)


In [39]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[7 7]
 [1 4]
 [2 0]]
(3, 2)


In [40]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 1 9]
 [5 7 6]]
(2, 3)


In [42]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[3 5]
 [1 7]
 [9 6]]
(3, 2)


In [43]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)


[[3 5]
 [1 7]
 [9 6]]
(3, 2)


In [44]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 9 3]
 [1 2 7]]
(2, 3)


In [45]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[2 1]
 [9 2]
 [3 7]]
(3, 2)


In [47]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 2 4]
 [4 7 4]]
(2, 3)


In [48]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 2]
 [4 4]
 [7 4]]
(3, 2)
